project 'MJStory.xcodeproj'
use_frameworks!
# Uncomment the next line to define a global platform for your project

target 'CTNotificationService' do  
    pod 'CTNotificationService'  
end   

target 'VMCTNotificationService' do
    pod 'CTNotificationService'  
end  

target 'MJStory' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks! :linkage => :static
  inherit! :search_paths
  platform :ios, '10.0'   

  pod 'FBSDKCoreKit', '6.5.2'
  pod 'FBSDKShareKit', '6.5.2'
  pod 'FBSDKLoginKit', '6.5.2'
  pod 'Firebase/Messaging' , '9.5.0'
  pod 'Firebase/DynamicLinks' , '9.5.0'
  pod 'Firebase/Analytics', '9.5.0'
  pod 'Firebase/RemoteConfig' , '9.5.0'
  pod 'Firebase/Auth' , '9.5.0'
  pod 'Firebase/Database' , '9.5.0'
  pod 'Firebase/Firestore', '9.5.0'
  pod 'Firebase/Crashlytics'
  pod 'CleverTap-iOS-SDK'
  pod 'GoogleSignIn', '5.0.2'
  pod 'AppsFlyerFramework'

end

target 'Monkey Stories' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Monkey Stories

end

target 'TruyenViet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TruyenViet

end

target 'VN Stories' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VN Stories
#  pod 'OneSignal', '>= 2.6.2', '< 3.0'
#  pod 'AccountKit'
  use_frameworks! :linkage => :static
  inherit! :search_paths
  platform :ios, '10.0'   
  #use_frameworks!

  pod 'FBSDKCoreKit', '6.5.2'
  pod 'FBSDKShareKit', '6.5.2'
  pod 'FBSDKLoginKit', '6.5.2'
  pod 'Firebase/Messaging' , '9.5.0'
  pod 'Firebase/DynamicLinks' , '9.5.0'
  pod 'Firebase/Analytics' , '9.5.0'
  pod 'Firebase/RemoteConfig' , '9.5.0'
  pod 'Firebase/Auth' , '9.5.0'
  pod 'Firebase/Database', '9.5.0'
  pod 'Firebase/Crashlytics'
  pod 'CleverTap-iOS-SDK'
  pod 'GoogleSignIn', '5.0.2'
  pod 'AppsFlyerFramework'

end
